#!/usr/bin/perl

# https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp-19
# https://tools.ietf.org/html/rfc7822

use strict;
use FindBin;
use lib "$FindBin::Bin/blib/lib";
use NTP::NTSKE;
use NTP::NTSKE::TLS;
use Getopt::Long;

my(%args,$debug,$contextfile,$draftexport);
GetOptions (
    "host=s"     => \$args{hostname},
    "port=i"     => \$args{port},
    "certfile=s" => \$args{certfile},
    "mintls=s"   => \$args{mintls},
    "debug"      => \$debug,
    "context=s"  => \$contextfile,
    "draft-export" => \$draftexport
    )
or die("Error in command line arguments\n");

if(not defined($contextfile)) {
  die("need context file\n");
}

foreach my $key (keys %args) {
  delete $args{$key} if not defined($args{$key});
}
if($debug) {
  $args{debug} = 1;
}
if($draftexport) {
  $args{exportConst} = "EXPORTER-network-time-security/1";
}

my($nts_tls) = NTP::NTSKE::TLS->new(%args);
my($nts) = NTP::NTSKE->new(tls => $nts_tls, debug => $debug);
my $context = $nts->get_context();
$context->save($contextfile);
print "saved to $contextfile\n";
