#!/usr/bin/perl

# https://tools.ietf.org/html/draft-ietf-ntp-using-nts-for-ntp-19
# https://tools.ietf.org/html/rfc7822

use strict;
use FindBin;
use lib "$FindBin::Bin/blib/lib";
use NTP::NTSKE;
use NTP::NTSKE::TLS;
use Getopt::Long;

my(%args,$debug);
GetOptions (
    "host=s"     => \$args{hostname},
    "port=i"     => \$args{port},
    "certfile=s" => \$args{certfile},
    "mintls=s"   => \$args{mintls},
    "debug"      => \$debug
    )
or die("Error in command line arguments\n");

foreach my $key (keys %args) {
  delete $args{$key} if not defined($args{$key});
}
if($debug) {
  $args{debug} = 1;
}

my($nts_tls) = NTP::NTSKE::TLS->new(%args);
my($nts) = NTP::NTSKE->new(tls => $nts_tls, debug => $debug);
my $context = $nts->get_cookie();
print "cookies:\n";
foreach my $cookie (@{ $context->cookie() }) {
  print unpack("H*", $cookie), "\n";
}
print "s2c:\n";
print unpack("H*", $context->s2c()),"\n";
print "c2s:\n";
print unpack("H*", $context->c2s()),"\n";
